language: python
python:
#  - 2.6
#  - 2.7
#  - pypy
#  - 3.1  # no longer supported on travis
#  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
script: python setup.py test

install:
#  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi
